#!/bin/sh
rm /usr/share/alsa/pcm/surround40.conf
rm /usr/share/alsa/pcm/dsnoop.conf
rm /usr/share/alsa/pcm/modem.conf
rm /usr/share/alsa/pcm/hdmi.conf
rm /usr/share/alsa/pcm/surround71.conf
rm /usr/share/alsa/pcm/center_lfe.conf
rm /usr/share/alsa/pcm/iec958.conf
rm /usr/share/alsa/pcm/surround41.conf
rm /usr/share/alsa/pcm/dpl.conf
rm /usr/share/alsa/pcm/side.conf
rm /usr/share/alsa/pcm/rear.conf
rm /usr/share/alsa/pcm/surround50.conf
rm /usr/share/alsa/pcm/front.conf
rm /usr/share/alsa/pcm/default.conf
rm /usr/share/alsa/pcm/dmix.conf
rm /usr/share/alsa/pcm/surround51.conf
rm /usr/share/alsa/sndo-mixer.alisp
rm /usr/share/alsa/smixer.conf
rm /usr/share/alsa/cards/ICH4.conf
rm /usr/share/alsa/cards/SB-XFi.conf
rm /usr/share/alsa/cards/CA0106.conf
rm /usr/share/alsa/cards/VIA686A.conf
rm /usr/share/alsa/cards/Audigy2.conf
rm /usr/share/alsa/cards/Aureon71.conf
rm /usr/share/alsa/cards/YMF744.conf
rm /usr/share/alsa/cards/USB-Audio.conf
rm /usr/share/alsa/cards/SI7018/sndop-mixer.alisp
rm /usr/share/alsa/cards/SI7018/sndoc-mixer.alisp
rm /usr/share/alsa/cards/ICH.conf
rm /usr/share/alsa/cards/PS3.conf
rm /usr/share/alsa/cards/Audigy.conf
rm /usr/share/alsa/cards/ENS1371.conf
rm /usr/share/alsa/cards/SI7018.conf
rm /usr/share/alsa/cards/RME9636.conf
rm /usr/share/alsa/cards/PC-Speaker.conf
rm /usr/share/alsa/cards/VX222.conf
rm /usr/share/alsa/cards/EMU10K1X.conf
rm /usr/share/alsa/cards/CMI8338-SWIEC.conf
rm /usr/share/alsa/cards/aliases.conf
rm /usr/share/alsa/cards/CMI8738-MC8.conf
rm /usr/share/alsa/cards/VIA8237.conf
rm /usr/share/alsa/cards/EMU10K1.conf
rm /usr/share/alsa/cards/ICE1724.conf
rm /usr/share/alsa/cards/CMI8338.conf
rm /usr/share/alsa/cards/FM801.conf
rm /usr/share/alsa/cards/AU8820.conf
rm /usr/share/alsa/cards/Aureon51.conf
rm /usr/share/alsa/cards/GUS.conf
rm /usr/share/alsa/cards/VIA8233A.conf
rm /usr/share/alsa/cards/ATIIXP.conf
rm /usr/share/alsa/cards/ENS1370.conf
rm /usr/share/alsa/cards/ICE1712.conf
rm /usr/share/alsa/cards/NFORCE.conf
rm /usr/share/alsa/cards/AU8810.conf
rm /usr/share/alsa/cards/AU8830.conf
rm /usr/share/alsa/cards/ATIIXP-SPDMA.conf
rm /usr/share/alsa/cards/RME9652.conf
rm /usr/share/alsa/cards/VIA8233.conf
rm /usr/share/alsa/cards/CS46xx.conf
rm /usr/share/alsa/cards/PMacToonie.conf
rm /usr/share/alsa/cards/Maestro3.conf
rm /usr/share/alsa/cards/CMI8738-MC6.conf
rm /usr/share/alsa/cards/TRID4DWAVENX.conf
rm /usr/share/alsa/cards/ATIIXP-MODEM.conf
rm /usr/share/alsa/cards/aliases.alisp
rm /usr/share/alsa/cards/VXPocket440.conf
rm /usr/share/alsa/cards/VXPocket.conf
rm /usr/share/alsa/cards/CMI8788.conf
rm /usr/share/alsa/cards/ICH-MODEM.conf
rm /usr/share/alsa/cards/HDA-Intel.conf
rm /usr/share/alsa/cards/AACI.conf
rm /usr/share/alsa/cards/ES1968.conf
rm /usr/share/alsa/cards/PMac.conf
rm /usr/share/alsa/alsa.conf
rm /usr/lib/alsa-lib/smixer/smixer-ac97.so
rm /usr/lib/alsa-lib/smixer/smixer-hda.so
rm /usr/lib/alsa-lib/smixer/smixer-sbase.so
rm /usr/lib/libasound.so.2.0.0
rm /usr/lib/libasound.so.2

rm -rvf /usr/share/alsa
rm -rvf /usr/lib/alsa-lib

